apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: 192.168.64.9.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
